baseURL = "https://mgx-metagenomics.github.io/"
theme = "hugo-whisper-theme"
languageCode = "en-us"
title = "MGX metagenome analysis platform"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 2
    
[[menu.main]]
    name = "About"
    url = "/docs/about"
    weight = 3

[[menu.main]]
    name = "Download"
    url = "https://github.com/MGX-metagenomics/MGX-gui/releases/tag/v20240109"
    weight = 3


[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Documentation'
  button_link='/docs/about/'
  button_text = 'About'
  homepage_intro = 'MGX metagenome analysis platform'
  homepage_image = '/images/slides/1.png'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "MGX metagenome analysis platform"
    meta_og_title = "MGX metagenome analysis platform"
    meta_og_type = "website"
    meta_og_url = "https://github.com/MGX-metagenomics"
    meta_og_image = "/images/mgx_logo_crapola.svg"
    meta_og_description = "MGX metagenome analysis platform"
    #meta_twitter_card = "summary"
    #meta_twitter_site = "@zerostaticio"
    #meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/mgx_logo_crapola.svg"
      standard  = "/images/mgx_logo_crapola.svg"

  [params.footer]
    copyright_text = '<a class="MGX" href="https://github.com/MGX-metagenomics">MGX</a>'

  [markup.goldmark.renderer]
    unsafe= true
    enableEmoji = true
  
  [markup.goldmark.parser.attribute]
    block = true 